/**
 * Printable W-2 and 1099-NEC form layouts for employee / IRS Copy B style filing.
 * Opens a print window; user can Save as PDF from the browser print dialog.
 */

function money(n) {
  return (Math.round((Number(n) || 0) * 100) / 100).toFixed(2);
}

function esc(s) {
  return String(s ?? '')
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;');
}

function printHtml(title, body) {
  const win = window.open('', '_blank', 'noopener');
  if (!win) return false;
  win.document.write(`<!DOCTYPE html><html><head><meta charset="utf-8"><title>${esc(title)}</title>
<style>
@page{size:letter;margin:.4in}
body{font:11px/1.35 Arial,Helvetica,sans-serif;color:#111;margin:0;padding:12px}
h1{font-size:16px;margin:0 0 8px}
.meta{color:#444;margin-bottom:12px;font-size:10px}
.grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}
.box{border:1px solid #222;padding:8px 10px;min-height:42px}
.box label{display:block;font-size:8px;text-transform:uppercase;color:#555;margin-bottom:3px}
.box b{font-size:13px}
.full{grid-column:1/-1}
.row3{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}
.notice{margin-top:14px;padding:8px;border:1px solid #999;background:#f7f7f7;font-size:9px}
@media print{button{display:none}}
button{margin-top:12px;padding:8px 14px}
</style></head><body>${body}<button type="button" onclick="window.print()">Print / Save as PDF</button></body></html>`);
  win.document.close();
  return true;
}

/**
 * @param {{
 *   taxYear: number,
 *   employer: { name: string, address: string, ein: string },
 *   employee: { name: string, address: string, ssnLast4?: string, employeeId?: string },
 *   wages: number, federal: number, socialSecurityWages: number, socialSecurity: number,
 *   medicareWages: number, medicare: number, state?: string, stateWages?: number, stateTax?: number
 * }} data
 */
export function openW2Form(data) {
  const y = data.taxYear || new Date().getFullYear();
  const body = `
<h1>Form W-2 Wage and Tax Statement — ${y}</h1>
<p class="meta">Copy B — To Be Filed With Employee’s FEDERAL Tax Return · Generated by MechPro for filing / SSA Business Services Online upload prep. Verify EIN and SSN before submitting.</p>
<div class="grid">
  <div class="box"><label>a Employee’s social security number</label><b>***-**-${esc(data.employee.ssnLast4 || 'XXXX')}</b></div>
  <div class="box"><label>b Employer identification number (EIN)</label><b>${esc(data.employer.ein || 'XX-XXXXXXX')}</b></div>
  <div class="box full"><label>c Employer’s name, address, and ZIP code</label><b>${esc(data.employer.name)}<br>${esc(data.employer.address)}</b></div>
  <div class="box"><label>e Employee’s first name and initial / Last name</label><b>${esc(data.employee.name)}</b></div>
  <div class="box"><label>Employee ID</label><b>${esc(data.employee.employeeId || '')}</b></div>
  <div class="box full"><label>f Employee’s address and ZIP code</label><b>${esc(data.employee.address || '')}</b></div>
</div>
<div class="row3" style="margin-top:8px">
  <div class="box"><label>1 Wages, tips, other compensation</label><b>${money(data.wages)}</b></div>
  <div class="box"><label>2 Federal income tax withheld</label><b>${money(data.federal)}</b></div>
  <div class="box"><label>3 Social security wages</label><b>${money(data.socialSecurityWages)}</b></div>
  <div class="box"><label>4 Social security tax withheld</label><b>${money(data.socialSecurity)}</b></div>
  <div class="box"><label>5 Medicare wages and tips</label><b>${money(data.medicareWages)}</b></div>
  <div class="box"><label>6 Medicare tax withheld</label><b>${money(data.medicare)}</b></div>
  <div class="box"><label>15 State</label><b>${esc(data.state || '')}</b></div>
  <div class="box"><label>16 State wages, tips, etc.</label><b>${money(data.stateWages || 0)}</b></div>
  <div class="box"><label>17 State income tax</label><b>${money(data.stateTax || 0)}</b></div>
</div>
<div class="notice">File Copy A electronically with SSA (ssa.gov/employer). Give Copies B, C, and 2 to the employee by January 31. MechPro generates this statement from shop payroll records; confirm SSN and EIN before e-filing.</div>`;
  return printHtml(`W-2 ${y} ${data.employee.name}`, body);
}

/**
 * @param {{
 *   taxYear: number,
 *   payer: { name: string, address: string, tin: string },
 *   recipient: { name: string, address: string, tinLast4?: string },
 *   nonemployeeCompensation: number, federalTaxWithheld?: number
 * }} data
 */
export function open1099NecForm(data) {
  const y = data.taxYear || new Date().getFullYear();
  const body = `
<h1>Form 1099-NEC Nonemployee Compensation — ${y}</h1>
<p class="meta">Copy B For Recipient · Generated by MechPro for IRS / recipient filing. File Copy A with the IRS (FIRE / IRIS) when required.</p>
<div class="grid">
  <div class="box"><label>PAYER’S name, street address, city, state, ZIP</label><b>${esc(data.payer.name)}<br>${esc(data.payer.address)}</b></div>
  <div class="box"><label>PAYER’S TIN</label><b>${esc(data.payer.tin || '')}</b></div>
  <div class="box"><label>RECIPIENT’S name</label><b>${esc(data.recipient.name)}</b></div>
  <div class="box"><label>RECIPIENT’S TIN</label><b>***-**-${esc(data.recipient.tinLast4 || 'XXXX')}</b></div>
  <div class="box full"><label>Street address (including apt. no.) / City, state, and ZIP code</label><b>${esc(data.recipient.address || '')}</b></div>
  <div class="box"><label>1 Nonemployee compensation</label><b>${money(data.nonemployeeCompensation)}</b></div>
  <div class="box"><label>4 Federal income tax withheld</label><b>${money(data.federalTaxWithheld || 0)}</b></div>
</div>
<div class="notice">File with the IRS when nonemployee compensation is $600 or more. Recipients use this for Schedule C / income reporting. MechPro does not transmit to IRS FIRE until transmitter credentials are configured; download the e-file package and submit via IRS IRIS/FIRE or your CPA.</div>`;
  return printHtml(`1099-NEC ${y} ${data.recipient.name}`, body);
}

/**
 * Minimal SSA EFW2-style fixed-width export (RA/RE/RW/RT/RF) for BSO upload prep.
 * Not a certified AccuWage validator — structure follows common EFW2 record types.
 */
export function buildEfw2Text(employer, employees, taxYear) {
  const pad = (s, n) => String(s ?? '').slice(0, n).padEnd(n, ' ');
  const num = (n, len) => String(Math.round((Number(n) || 0) * 100)).padStart(len, '0').slice(-len);
  const ein = String(employer.ein || '').replace(/\D/g, '').padStart(9, '0').slice(0, 9);
  const lines = [];
  lines.push(`RA${pad(ein, 9)}${pad(employer.name, 57)}${pad(employer.address, 40)}${pad('', 194)}`);
  lines.push(`RE${taxYear}${pad(ein, 9)}${pad(employer.name, 57)}${pad(employer.address, 40)}${pad('', 192)}`);
  let totalWages = 0; let totalFit = 0; let totalSs = 0; let totalMed = 0; let count = 0;
  for (const emp of employees) {
    count += 1;
    totalWages += Number(emp.wages) || 0;
    totalFit += Number(emp.federal) || 0;
    totalSs += Number(emp.socialSecurity) || 0;
    totalMed += Number(emp.medicare) || 0;
    const ssn = String(emp.ssn || '').replace(/\D/g, '').padStart(9, '0').slice(0, 9);
    lines.push(
      `RW${ssn}${pad(emp.lastName || emp.name || '', 20)}${pad(emp.firstName || '', 15)}`
      + `${num(emp.wages, 11)}${num(emp.federal, 11)}${num(emp.socialSecurityWages, 11)}${num(emp.socialSecurity, 11)}`
      + `${num(emp.medicareWages ?? emp.wages, 11)}${num(emp.medicare, 11)}${pad('', 198)}`,
    );
  }
  lines.push(`RT${String(count).padStart(7, '0')}${num(totalWages, 15)}${num(totalFit, 15)}${num(totalSs, 15)}${num(totalMed, 15)}${pad('', 449)}`);
  lines.push(`RF${String(count).padStart(9, '0')}${pad('', 503)}`);
  return lines.join('\r\n');
}
