/**
 * Shared MechPro client configuration.
 * Generated by scripts/sync-frontend-config.mjs — do not edit by hand.
 * Source: MECHPRO_API_URL (defaults to same-origin /api)
 */
export const cloudflareConfig = Object.freeze({
  auth: 'cloudflare-access',
  apiUrl: '/api',
});

export const storageKeys = Object.freeze({
  dispatch: 'mechpro-dispatch-v1',
  session: 'mechpro-session',
  mutationQueue: 'mechpro-mutation-queue-v1',
});

if (typeof globalThis !== 'undefined') {
  globalThis.__MECHPRO_CONFIG__ = { cloudflare: cloudflareConfig, storage: storageKeys };
}
