/**
 * Shared MechPro client configuration.
 * Generated by scripts/sync-frontend-config.mjs — do not edit by hand.
 * Source: MECHPRO_API_URL (defaults to same-origin /api)
 */
export const cloudflareConfig = Object.freeze({
  auth: 'mechpro-saas',
  apiUrl: '/api',
  authEndpoints: {
    magicLink: '/api/auth/magic-link',
    callback: '/api/auth/callback',
    session: '/api/auth/session',
    logout: '/api/auth/logout',
  },
});

export const storageKeys = Object.freeze({
  dispatch: 'mechpro-dispatch-v1',
  session: 'mechpro-session',
  mutationQueue: 'mechpro-mutation-queue-v1',
});
